import { initializeApp } from "firebase/app";
import { getFirestore, setDoc, doc, serverTimestamp } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyCb_jCMZ2yx4po0ddGxJbrny4PGzw5RNTw",
  authDomain: "krishi-queue-full.firebaseapp.com",
  projectId: "krishi-queue-full",
  storageBucket: "krishi-queue-full.firebasestorage.app",
  messagingSenderId: "266215195781",
  appId: "1:266215195781:web:9dc4d3cf66272e704315ec",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const PAN_INDIA_NEW_CENTERS = [
  // Uttar Pradesh - Naini & Prayagraj
  {
    docId: "kums_naini_prayagraj",
    code: "UP-PRY-02",
    name: "KUMS Naini Sub-Yard, Prayagraj",
    location: "Mirzapur Highway, Naini Industrial Area",
    district: "Prayagraj",
    state: "Uttar Pradesh",
    pincode: "211008",
    latitude: 25.3855,
    longitude: 81.8700,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "750 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_mundera_prayagraj",
    code: "UP-PRY-01",
    name: "KUMS Mundera Main Mandi, Prayagraj",
    location: "GT Road Mundera, Prayagraj (Near Naini)",
    district: "Prayagraj",
    state: "Uttar Pradesh",
    pincode: "211011",
    latitude: 25.4612,
    longitude: 81.7745,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,200 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Maharashtra
  {
    docId: "apmc_lasalgaon_nashik",
    code: "MH-NSK-01",
    name: "APMC Lasalgaon Main Yard, Nashik",
    location: "Station Road, Lasalgaon (Asia's Largest Onion Hub)",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422306",
    latitude: 20.1472,
    longitude: 74.2289,
    activeBays: "10 / 10 Bays Active",
    dailyCapacity: "2,500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_pimpalgaon_nashik",
    code: "MH-NSK-02",
    name: "APMC Pimpalgaon Baswant, Nashik",
    location: "NH-3 Agra Road, Pimpalgaon Baswant",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422209",
    latitude: 20.1712,
    longitude: 73.9854,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,800 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_gultekdi_pune",
    code: "MH-PUN-01",
    name: "APMC Gultekdi Market Yard, Pune",
    location: "Gultekdi, Swargate Outer, Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411037",
    latitude: 18.4952,
    longitude: 73.8685,
    activeBays: "12 / 12 Bays Active",
    dailyCapacity: "3,000 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_baramati_pune",
    code: "MH-PUN-02",
    name: "APMC Baramati Grain Terminal, Pune",
    location: "Indapur Road, Baramati Sub-Division",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413102",
    latitude: 18.1512,
    longitude: 74.5772,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,100 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_kalamna_nagpur",
    code: "MH-NGP-01",
    name: "APMC Kalamna Cotton & Grain Market, Nagpur",
    location: "Kalamna Market Yard, Bhandara Road, Nagpur",
    district: "Nagpur",
    state: "Maharashtra",
    pincode: "440035",
    latitude: 21.1712,
    longitude: 79.1412,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,900 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_latur_pulses",
    code: "MH-LTR-01",
    name: "APMC Latur Pulses & Oilseed Hub, Latur",
    location: "Ausa Road, Latur City",
    district: "Latur",
    state: "Maharashtra",
    pincode: "413512",
    latitude: 18.4088,
    longitude: 76.5604,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Gujarat
  {
    docId: "apmc_unjha_mehsana",
    code: "GJ-MSH-01",
    name: "APMC Unjha Spice & Cumin Yard, Mehsana",
    location: "Ganj Bazar, Unjha (Asia's Cumin Capital)",
    district: "Mehsana",
    state: "Gujarat",
    pincode: "384170",
    latitude: 23.8041,
    longitude: 72.3921,
    activeBays: "10 / 10 Bays Active",
    dailyCapacity: "2,200 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_gondal_rajkot",
    code: "GJ-RJK-01",
    name: "APMC Gondal Market Yard, Rajkot",
    location: "National Highway 27, Gondal",
    district: "Rajkot",
    state: "Gujarat",
    pincode: "360311",
    latitude: 21.9612,
    longitude: 70.7954,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,800 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_bedi_rajkot",
    code: "GJ-RJK-02",
    name: "APMC Rajkot Bedi Yard, Rajkot",
    location: "Bedi Gaon Road, Morbi Highway, Rajkot",
    district: "Rajkot",
    state: "Gujarat",
    pincode: "360003",
    latitude: 22.3412,
    longitude: 70.8124,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_jamalpur_ahmedabad",
    code: "GJ-AMD-01",
    name: "APMC Jamalpur Terminal, Ahmedabad",
    location: "Jamalpur Gate, Sardar Bridge End, Ahmedabad",
    district: "Ahmedabad",
    state: "Gujarat",
    pincode: "380022",
    latitude: 23.0112,
    longitude: 72.5841,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Bihar
  {
    docId: "bazar_samiti_gulabbagh_purnea",
    code: "BR-PUR-01",
    name: "Bazar Samiti Gulabbagh Maize Hub, Purnea",
    location: "Gulabbagh Mandi Campus (Asia's Maize Hub)",
    district: "Purnea",
    state: "Bihar",
    pincode: "854326",
    latitude: 25.7812,
    longitude: 87.5214,
    activeBays: "10 / 10 Bays Active",
    dailyCapacity: "2,800 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "bazar_samiti_mithapur_patna",
    code: "BR-PAT-01",
    name: "Bazar Samiti Mithapur Yard, Patna",
    location: "Bypass Road, Mithapur, Patna",
    district: "Patna",
    state: "Bihar",
    pincode: "800001",
    latitude: 25.5941,
    longitude: 85.1376,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,200 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "bazar_samiti_muzaffarpur",
    code: "BR-MUZ-01",
    name: "Bazar Samiti Muzaffarpur Grain Mandi",
    location: "Kanti Road, Muzaffarpur City",
    district: "Muzaffarpur",
    state: "Bihar",
    pincode: "842001",
    latitude: 26.1209,
    longitude: 85.3647,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,100 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // West Bengal
  {
    docId: "rmc_matigara_siliguri",
    code: "WB-DAR-01",
    name: "Siliguri Regulated Market Committee, Matigara",
    location: "Matigara Sub-Division, NH-31, Siliguri",
    district: "Darjeeling",
    state: "West Bengal",
    pincode: "734010",
    latitude: 26.7112,
    longitude: 88.3912,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "rmc_burdwan",
    code: "WB-BRD-01",
    name: "Burdwan Regulated Market Yard, Purba Bardhaman",
    location: "Mandi Road, Burdwan Town",
    district: "Purba Bardhaman",
    state: "West Bengal",
    pincode: "713101",
    latitude: 23.2324,
    longitude: 87.8615,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "2,100 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Karnataka
  {
    docId: "apmc_yeshwantpur_bengaluru",
    code: "KA-BLR-01",
    name: "APMC Yeshwantpur Sub-Yard, Bengaluru",
    location: "Tumkur Road, Yeshwantpur, Bengaluru Urban",
    district: "Bengaluru Urban",
    state: "Karnataka",
    pincode: "560022",
    latitude: 13.0285,
    longitude: 77.5452,
    activeBays: "12 / 12 Bays Active",
    dailyCapacity: "2,600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_amargol_hubballi",
    code: "KA-DHR-01",
    name: "APMC Amargol Market Yard, Hubballi",
    location: "PB Road, Amargol, Hubballi",
    district: "Dharwad",
    state: "Karnataka",
    pincode: "580025",
    latitude: 15.3912,
    longitude: 75.1012,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,700 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_davanagere",
    code: "KA-DVG-01",
    name: "APMC Davanagere Maize & Paddy Hub",
    location: "Hadadi Road, Davanagere",
    district: "Davanagere",
    state: "Karnataka",
    pincode: "577002",
    latitude: 14.4644,
    longitude: 75.9218,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,400 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Tamil Nadu
  {
    docId: "rmc_coimbatore_trichyroad",
    code: "TN-CBE-01",
    name: "APMC Coimbatore RMC Trichy Road",
    location: "Trichy Road, Singanallur, Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641018",
    latitude: 11.0012,
    longitude: 76.9612,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "rmc_mattuthavani_madurai",
    code: "TN-MDU-01",
    name: "APMC Mattuthavani Regulated Market, Madurai",
    location: "Mattuthavani Bus Stand Road, Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    pincode: "625007",
    latitude: 9.9412,
    longitude: 78.1512,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,200 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Andhra Pradesh
  {
    docId: "apmc_guntur_mirchi",
    code: "AP-GNT-01",
    name: "APMC Guntur Mirchi Yard (Asia's Chilli Hub)",
    location: "Narakodur Road, Guntur City",
    district: "Guntur",
    state: "Andhra Pradesh",
    pincode: "522004",
    latitude: 16.3067,
    longitude: 80.4365,
    activeBays: "14 / 14 Bays Active",
    dailyCapacity: "4,000 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Telangana
  {
    docId: "apmc_nizamabad_turmeric",
    code: "TG-NZB-01",
    name: "APMC Nizamabad Turmeric & Paddy Yard",
    location: "Bodhan Road, Nizamabad",
    district: "Nizamabad",
    state: "Telangana",
    pincode: "503001",
    latitude: 18.6725,
    longitude: 78.0941,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,800 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_enumamula_warangal",
    code: "TG-WGL-01",
    name: "APMC Enumamula Grain Market, Warangal",
    location: "Mulugu Road, Enumamula, Warangal",
    district: "Hanamkonda",
    state: "Telangana",
    pincode: "506013",
    latitude: 17.9812,
    longitude: 79.6212,
    activeBays: "10 / 10 Bays Active",
    dailyCapacity: "2,500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Assam
  {
    docId: "rmc_pamohi_guwahati",
    code: "AS-GHY-01",
    name: "Pamohi Regulated Market, Guwahati",
    location: "Gorchuk Pamohi, Kamrup Metropolitan, Guwahati",
    district: "Kamrup Metropolitan",
    state: "Assam",
    pincode: "781035",
    latitude: 26.1112,
    longitude: 91.6812,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,000 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Odisha
  {
    docId: "rmc_khetrajpur_sambalpur",
    code: "OD-SBP-01",
    name: "RMC Khetrajpur Grain Yard, Sambalpur",
    location: "Khetrajpur Station Area, Sambalpur",
    district: "Sambalpur",
    state: "Odisha",
    pincode: "768003",
    latitude: 21.4912,
    longitude: 83.9712,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,200 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Jharkhand
  {
    docId: "bazar_samiti_pandra_ranchi",
    code: "JH-RNC-01",
    name: "Krishi Bazar Samiti Pandra, Ranchi",
    location: "Ratu Road, Pandra, Ranchi",
    district: "Ranchi",
    state: "Jharkhand",
    pincode: "834005",
    latitude: 23.3812,
    longitude: 85.2812,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,150 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Chhattisgarh
  {
    docId: "kums_tilda_raipur",
    code: "CG-RPR-01",
    name: "KUMS Tilda Mandi Hub, Raipur",
    location: "Baloda Bazar Road, Tilda, Raipur",
    district: "Raipur",
    state: "Chhattisgarh",
    pincode: "493114",
    latitude: 21.5612,
    longitude: 81.7912,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Kerala
  {
    docId: "apmc_aluva_kochi",
    code: "KL-EKM-01",
    name: "Aluva APMC Market, Ernakulam",
    location: "Bank Junction, Aluva, Kochi",
    district: "Ernakulam",
    state: "Kerala",
    pincode: "683101",
    latitude: 10.1076,
    longitude: 76.3516,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "900 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Himachal Pradesh
  {
    docId: "apmc_dhalli_shimla",
    code: "HP-SML-01",
    name: "APMC Dhalli Fruit & Grain Yard, Shimla",
    location: "Sanjauli-Dhalli Bypass, Shimla",
    district: "Shimla",
    state: "Himachal Pradesh",
    pincode: "171012",
    latitude: 31.1112,
    longitude: 77.2012,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,050 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Jammu & Kashmir
  {
    docId: "apmc_narwal_jammu",
    code: "JK-JAM-01",
    name: "APMC Narwal Mandi, Jammu",
    location: "Narwal Bypass Road, Jammu",
    district: "Jammu",
    state: "Jammu and Kashmir",
    pincode: "180006",
    latitude: 32.7012,
    longitude: 74.8812,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "1,100 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Uttarakhand
  {
    docId: "mandi_rudrapur_usnagar",
    code: "UK-USN-01",
    name: "Mandi Samiti Rudrapur, Udham Singh Nagar",
    location: "Kashipur Bypass Road, Rudrapur",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "263153",
    latitude: 28.9812,
    longitude: 79.4012,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "1,600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // Delhi NCR
  {
    docId: "apmc_azadpur_delhi",
    code: "DL-AZD-01",
    name: "Azadpur APMC Mandi, North Delhi",
    location: "Outer Ring Road, Azadpur, Delhi",
    district: "North Delhi",
    state: "Delhi",
    pincode: "110033",
    latitude: 28.7112,
    longitude: 77.1712,
    activeBays: "16 / 16 Bays Active",
    dailyCapacity: "5,000 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
];

async function seedPanIndia() {
  console.log(`Seeding ${PAN_INDIA_NEW_CENTERS.length} Pan-India APMC centers into Firestore...`);
  let count = 0;
  for (const c of PAN_INDIA_NEW_CENTERS) {
    const { docId, ...data } = c;
    await setDoc(doc(db, "centers", docId), {
      ...data,
      updatedAt: serverTimestamp(),
    }, { merge: true });
    count++;
    console.log(`[${count}/${PAN_INDIA_NEW_CENTERS.length}] Seeded: ${c.name} (${c.district}, ${c.state})`);
  }
  console.log(`Successfully seeded ${count} Pan-India APMC centers!`);
  process.exit(0);
}

seedPanIndia().catch((err) => {
  console.error("Failed to seed Pan-India centers:", err);
  process.exit(1);
});
