import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, setDoc, doc, serverTimestamp } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyCb_jCMZ2yx4po0ddGxJbrny4PGzw5RNTw",
  authDomain: "krishi-queue-full.firebaseapp.com",
  projectId: "krishi-queue-full",
  storageBucket: "krishi-queue-full.firebasestorage.app",
  messagingSenderId: "266215195781",
  appId: "1:266215195781:web:9dc4d3cf66272e704315ec",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

export const ALL_CENTERS = [
  // ==========================================
  // MADHYA PRADESH (Jabalpur, Singrauli, Rewa, Katni, Satna, Bhopal, Indore, etc.)
  // ==========================================
  {
    docId: "kums_adhartal_jabalpur",
    code: "MP-JBP-01",
    name: "KUMS Adhartal Main Mandi, Jabalpur",
    location: "Industrial Area, Adhartal Mandi Complex",
    district: "Jabalpur",
    state: "Madhya Pradesh",
    latitude: 23.2045,
    longitude: 79.9654,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "650 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_patan_jabalpur",
    code: "MP-JBP-02",
    name: "KUMS Patan Mandi Yard, Jabalpur",
    location: "Mandi Road, Patan Sub-Division",
    district: "Jabalpur",
    state: "Madhya Pradesh",
    latitude: 23.2842,
    longitude: 79.6895,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "400 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_sihora_jabalpur",
    code: "MP-JBP-03",
    name: "KUMS Sihora Grain Terminal, Jabalpur",
    location: "NH-30 Sihora Bypass Mandi Yard",
    district: "Jabalpur",
    state: "Madhya Pradesh",
    latitude: 23.4912,
    longitude: 80.1124,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_shahpura_jabalpur",
    code: "MP-JBP-04",
    name: "KUMS Shahpura Bhitoni Yard, Jabalpur",
    location: "Bhitoni Station Road Mandi Yard",
    district: "Jabalpur",
    state: "Madhya Pradesh",
    latitude: 23.1415,
    longitude: 79.6631,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "350 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_waidhan_singrauli",
    code: "MP-SNG-01",
    name: "KUMS Waidhan Main Mandi, Singrauli",
    location: "Collectorate Road Mandi Campus, Waidhan",
    district: "Singrauli",
    state: "Madhya Pradesh",
    latitude: 24.0625,
    longitude: 82.6285,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "450 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_morwa_singrauli",
    code: "MP-SNG-02",
    name: "KUMS Morwa Sub-Yard, Singrauli",
    location: "Railway Colony Road, Morwa Yard",
    district: "Singrauli",
    state: "Madhya Pradesh",
    latitude: 24.2041,
    longitude: 82.7214,
    activeBays: "3 / 4 Bays Active",
    dailyCapacity: "300 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_deosar_singrauli",
    code: "MP-SNG-03",
    name: "KUMS Deosar Mandi Yard, Singrauli",
    location: "Tehsil Road Mandi Yard, Deosar",
    district: "Singrauli",
    state: "Madhya Pradesh",
    latitude: 24.2185,
    longitude: 82.2612,
    activeBays: "3 / 4 Bays Active",
    dailyCapacity: "300 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_karahiya_rewa",
    code: "MP-REW-01",
    name: "KUMS Karahiya Main Mandi, Rewa",
    location: "Karahiya Mandi Complex, Rewa",
    district: "Rewa",
    state: "Madhya Pradesh",
    latitude: 24.5362,
    longitude: 81.3037,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_baikunthpur_rewa",
    code: "MP-REW-02",
    name: "KUMS Baikunthpur Yard, Rewa",
    location: "Sirmour Road Mandi Depot, Baikunthpur",
    district: "Rewa",
    state: "Madhya Pradesh",
    latitude: 24.7121,
    longitude: 81.3854,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "350 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_mangawan_rewa",
    code: "MP-REW-03",
    name: "KUMS Mangawan Sub-Yard, Rewa",
    location: "NH-30 Junction Yard, Mangawan",
    district: "Rewa",
    state: "Madhya Pradesh",
    latitude: 24.6781,
    longitude: 81.5432,
    activeBays: "3 / 4 Bays Active",
    dailyCapacity: "300 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_madhavnagar_katni",
    code: "MP-KTN-01",
    name: "KUMS Madhavnagar Mandi, Katni",
    location: "Madhavnagar Mandi Prangan, Katni",
    district: "Katni",
    state: "Madhya Pradesh",
    latitude: 23.8341,
    longitude: 80.3982,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_satna_main",
    code: "MP-STN-01",
    name: "KUMS Satna Main Mandi, Satna",
    location: "Panna Naka Mandi Complex, Satna",
    district: "Satna",
    state: "Madhya Pradesh",
    latitude: 24.5824,
    longitude: 80.8291,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "550 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_karond_bhopal",
    code: "MP-BPL-01",
    name: "KUMS Karond Mandi, Bhopal",
    location: "Berasia Road Mandi Yard, Karond",
    district: "Bhopal",
    state: "Madhya Pradesh",
    latitude: 23.3032,
    longitude: 77.4124,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "700 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_laxmibai_nagar_indore",
    code: "MP-IND-01",
    name: "KUMS Laxmibai Nagar Mandi, Indore",
    location: "Sanwer Road Mandi Complex, Laxmibai Nagar",
    district: "Indore",
    state: "Madhya Pradesh",
    latitude: 22.7533,
    longitude: 75.8637,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "850 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_chimanganj_ujjain",
    code: "MP-UJN-01",
    name: "KUMS Chimanganj Mandi, Ujjain",
    location: "Agar Road Mandi Campus, Chimanganj",
    district: "Ujjain",
    state: "Madhya Pradesh",
    latitude: 23.2014,
    longitude: 75.7925,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "650 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_gadarwara_narsinghpur",
    code: "MP-NSP-01",
    name: "KUMS Gadarwara Mandi, Narsinghpur",
    location: "Station Road Mandi Yard, Gadarwara",
    district: "Narsinghpur",
    state: "Madhya Pradesh",
    latitude: 22.9212,
    longitude: 78.7845,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_sagar_main",
    code: "MP-SGR-01",
    name: "KUMS Sagar Main Mandi, Sagar",
    location: "Bina-Sagar Road, Makronia Yard, Sagar",
    district: "Sagar",
    state: "Madhya Pradesh",
    latitude: 23.8388,
    longitude: 78.7378,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "550 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_sehore_main",
    code: "MP-SEH-01",
    name: "KUMS Sehore Mandi, Sehore",
    location: "Bhopal-Indore Highway Yard, Sehore",
    district: "Sehore",
    state: "Madhya Pradesh",
    latitude: 23.2031,
    longitude: 77.0844,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_vidisha_main",
    code: "MP-VID-01",
    name: "KUMS Vidisha Mandi, Vidisha",
    location: "Ahmedpur Road, Mandi Yard, Vidisha",
    district: "Vidisha",
    state: "Madhya Pradesh",
    latitude: 23.5251,
    longitude: 77.8105,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_itarsi_narmadapuram",
    code: "MP-NMD-01",
    name: "KUMS Itarsi Mandi, Narmadapuram",
    location: "Hoshangabad Road Mandi Depot, Itarsi",
    district: "Narmadapuram",
    state: "Madhya Pradesh",
    latitude: 22.6120,
    longitude: 77.7610,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "450 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "kums_lashkar_gwalior",
    code: "MP-GWL-01",
    name: "KUMS Lashkar Mandi, Gwalior",
    location: "Lashkar Mandi Complex, Gwalior",
    district: "Gwalior",
    state: "Madhya Pradesh",
    latitude: 26.2183,
    longitude: 78.1828,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // ==========================================
  // UTTAR PRADESH
  // ==========================================
  {
    docId: "up_mundera_prayagraj",
    code: "UP-PRY-01",
    name: "Mandi Samiti Mundera, Prayagraj",
    location: "GT Road, Mundera Mandi Complex",
    district: "Prayagraj",
    state: "Uttar Pradesh",
    latitude: 25.4358,
    longitude: 81.7915,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "up_paharika_varanasi",
    code: "UP-VNS-01",
    name: "Mandi Samiti Paharika, Varanasi",
    location: "Paharika Mandi Yard, Varanasi",
    district: "Varanasi",
    state: "Uttar Pradesh",
    latitude: 25.3176,
    longitude: 82.9739,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "up_dubagga_lucknow",
    code: "UP-LKO-01",
    name: "Mandi Samiti Dubagga, Lucknow",
    location: "Hardoi Road, Dubagga Mandi Yard",
    district: "Lucknow",
    state: "Uttar Pradesh",
    latitude: 26.8606,
    longitude: 80.8660,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "650 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "up_naubasta_kanpur",
    code: "UP-KNP-01",
    name: "Mandi Samiti Naubasta, Kanpur",
    location: "Hamirpur Road, Naubasta Mandi Complex",
    district: "Kanpur",
    state: "Uttar Pradesh",
    latitude: 26.4024,
    longitude: 80.3319,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "up_sikandra_agra",
    code: "UP-AGR-01",
    name: "Mandi Samiti Sikandra, Agra",
    location: "NH-19 Sikandra Mandi Depot, Agra",
    district: "Agra",
    state: "Uttar Pradesh",
    latitude: 27.2152,
    longitude: 77.9392,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // ==========================================
  // PUNJAB
  // ==========================================
  {
    docId: "pb_khanna_ludhiana",
    code: "PB-LDH-01",
    name: "Khanna APMC Grain Market, Ludhiana",
    location: "GT Road Grain Terminal, Khanna",
    district: "Ludhiana",
    state: "Punjab",
    latitude: 30.7067,
    longitude: 76.2206,
    activeBays: "8 / 8 Bays Active",
    dailyCapacity: "900 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "pb_rajpura_patiala",
    code: "PB-PTL-01",
    name: "Rajpura Grain Market Yard, Patiala",
    location: "Ambala-Rajpura Highway Mandi, Rajpura",
    district: "Patiala",
    state: "Punjab",
    latitude: 30.4842,
    longitude: 76.5941,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "550 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "pb_bathinda_grain",
    code: "PB-BTI-01",
    name: "Bathinda APMC Grain Market, Bathinda",
    location: "Mansa Road Yard, Bathinda",
    district: "Bathinda",
    state: "Punjab",
    latitude: 30.2110,
    longitude: 74.9455,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // ==========================================
  // RAJASTHAN
  // ==========================================
  {
    docId: "rj_bhamashah_kota",
    code: "RJ-KTA-01",
    name: "Kota APMC Bhamashah Mandi, Kota",
    location: "Anantpura, Kota Mandi Yard",
    district: "Kota",
    state: "Rajasthan",
    latitude: 25.1384,
    longitude: 75.8648,
    activeBays: "7 / 7 Bays Active",
    dailyCapacity: "750 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "rj_muhana_jaipur",
    code: "RJ-JPR-01",
    name: "Jaipur APMC Muhana Mandi, Jaipur",
    location: "Sanganer-Muhana Terminal, Jaipur",
    district: "Jaipur",
    state: "Rajasthan",
    latitude: 26.7950,
    longitude: 75.7610,
    activeBays: "7 / 7 Bays Active",
    dailyCapacity: "700 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "rj_sri_ganganagar",
    code: "RJ-SGG-01",
    name: "Sri Ganganagar Grain Market Hub",
    location: "Suratgarh Road Depot, Sri Ganganagar",
    district: "Sri Ganganagar",
    state: "Rajasthan",
    latitude: 29.9038,
    longitude: 73.8772,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "650 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },

  // ==========================================
  // HARYANA
  // ==========================================
  {
    docId: "apmc_karnal_main",
    code: "APMC-KRN-01",
    name: "APMC Karnal Main Hub, Karnal",
    location: "Main Mandi Complex, GT Road",
    district: "Karnal",
    state: "Haryana",
    latitude: 29.6857,
    longitude: 76.9905,
    activeBays: "6 / 6 Bays Active",
    dailyCapacity: "600 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_taraori_yard",
    code: "APMC-TR-02",
    name: "Taraori Grain Market Hub, Karnal",
    location: "Railway Road, Near Gate 2",
    district: "Karnal",
    state: "Haryana",
    latitude: 29.8052,
    longitude: 76.9288,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "400 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_gharaunda_yard",
    code: "APMC-GHR-03",
    name: "Gharaunda Procurement Yard, Karnal",
    location: "NH-44 Bypass Mandi Complex",
    district: "Karnal",
    state: "Haryana",
    latitude: 29.5398,
    longitude: 76.9712,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "450 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_assandh_yard",
    code: "APMC-ASD-04",
    name: "Assandh Grain Market Hub, Karnal",
    location: "Jind Road Mandi Yard",
    district: "Karnal",
    state: "Haryana",
    latitude: 29.5218,
    longitude: 76.6022,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "350 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_indri_yard",
    code: "APMC-IND-05",
    name: "Indri Silo & Procurement Center, Karnal",
    location: "Ladwa-Indri Link Road",
    district: "Karnal",
    state: "Haryana",
    latitude: 29.8824,
    longitude: 77.0601,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_nilokheri_yard",
    code: "APMC-NLK-06",
    name: "Nilokheri APMC Sub-Yard, Karnal",
    location: "Station Road, Grain Depot",
    district: "Karnal",
    state: "Haryana",
    latitude: 29.8333,
    longitude: 76.9167,
    activeBays: "3 / 4 Bays Active",
    dailyCapacity: "300 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_panipat_yard",
    code: "APMC-PNP-07",
    name: "Panipat APMC Grain Market, Panipat",
    location: "GT Karnal Road Terminal",
    district: "Panipat",
    state: "Haryana",
    latitude: 29.3909,
    longitude: 76.9635,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "550 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_kurukshetra_yard",
    code: "APMC-KRK-08",
    name: "Kurukshetra APMC Grain Market, Kurukshetra",
    location: "Pipli Road Grain Terminal",
    district: "Kurukshetra",
    state: "Haryana",
    latitude: 29.9695,
    longitude: 76.8783,
    activeBays: "4 / 4 Bays Active",
    dailyCapacity: "450 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
  {
    docId: "apmc_kaithal_yard",
    code: "APMC-KTH-09",
    name: "Kaithal APMC Mandi Complex, Kaithal",
    location: "Ambala-Hissar Bypass",
    district: "Kaithal",
    state: "Haryana",
    latitude: 29.8015,
    longitude: 76.3996,
    activeBays: "5 / 5 Bays Active",
    dailyCapacity: "500 Q / day",
    currentInflow: "0 Q",
    status: "Active",
  },
];

async function seedAllCenters() {
  console.log(`Starting to seed ${ALL_CENTERS.length} APMC procurement centers into Firestore...`);
  const centersCol = collection(db, "centers");

  const existingSnap = await getDocs(centersCol);
  console.log(`Currently found ${existingSnap.size} existing centers in Firestore.`);

  let written = 0;
  for (const center of ALL_CENTERS) {
    const { docId, ...data } = center;
    const docRef = doc(db, "centers", docId);
    await setDoc(docRef, {
      ...data,
      createdAt: serverTimestamp(),
    }, { merge: true });
    written++;
  }

  console.log(`Successfully wrote/updated ${written} official APMC centers in Firestore!`);

  // Verify total centers
  const finalSnap = await getDocs(centersCol);
  console.log(`Final Firestore centers count: ${finalSnap.size}`);

  const mpCenters = finalSnap.docs.filter(d => d.data().state === "Madhya Pradesh");
  console.log(`Madhya Pradesh centers count in DB: ${mpCenters.length}`);

  process.exit(0);
}

seedAllCenters().catch(err => {
  console.error("Error seeding centers:", err);
  process.exit(1);
});
